### ISSUE TITLE
Local tests diaplay a passing result for code that fails to compile

### ISSUE THREAD

**Issue by SunnyWebeSimile** [rage/tmc-cli-rust#29]
Issue encountered on Part05_01: OneMinute exercise of Java MOOC. Running tmc test for an exercise here when a syntax error prevents compilation of .java file shows:

```
Testing: part05-Part05_01.OneMinute

Test results: 0/0 tests passed
**All tests passed! Submit to server with 'tmc submit'**
 100%[progress bar]

```

Misleading, has induced several failed submissions from me already. With code that compiles successfully, there being 5 test cases is reflected correctly.

Recommend that a separate error message is thrown on compile failure. (This is handled correctly by the Java tmc-cli)

**Comment by Heliozoa** [comment]
Thanks for reporting this issue! The test results data was being interpreted improperly so that compilation errors were not being handled at all.

I've just released v1.1.2 where this issue should be fixed.
